default:
  # the followings are required for numerical stability for iteratively estimating means and vars
  min_mean: 1.0e-7
  max_mean: 1.0e+7
  effect_size_negative_lb: -1.0e+7
  
  max_var: 1.0e+4
  min_var: 1.0e-4

  nloptr_local_maxeval: 150
  nloptr_local_xtol_rel: 1.0e-8
 
  nloptr_global_maxeval: 150
  nloptr_global_xtol_rel: 1.0e-8
 
  nloptr_grad_check_derivatives: FALSE
  nloptr_candidate_algs: NLOPT_LN_COBYLA;NLOPT_LN_BOBYQA

  epsilon: 1.0e-4
  
  type: "timer" # change to "none" to supress the progress bars (this will result is some speed up of the running time)
  nout: 10  # the resolution of the progress bars (higher values -> highr resolution but increased overhead, which in turns results in longer running time)
